server:
  port: 9010

spring:
  application:
    name: xss-gateway
  main:
      web-application-type: reactive
  config:
      import: application.yml
  cloud:
    nacos:
      config:
        import-check:
            enabled: false
      discovery:
        server-addr: http://101.200.213.75:8848
    gateway:
      routes:
        - id: xss-user             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8088    #匹配后提供服务的路由地址
          predicates:
            - Path=/xss-user/**    #断言，路径相匹配的进行路由




