server:
  port: 9010

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  config:
    import: application.yml
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: http://localhost:8848

    gateway:
      routes:
        - id: user-service             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9020    #匹配后提供服务的路由地址
          predicates:
            - Path=/user-service/**    #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1
        - id: order-service             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9030    #匹配后提供服务的路由地址
          predicates:
            - Path=/order-service/**    #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1


