server:
  port: 9030
spring:
  application:
    name: order-service
  profiles:
    #        多个文件用，隔开
    active: shardingTable
  cloud:
    nacos:
      config:
        enabled: false
        #        配置中心地址
        server-addr:
      discovery:
        server-addr: http://localhost:8848


# 开启feign对sentinel的支持
feign:
  compression:
    request:
      # 开启请求压缩
      enabled: true
      # 配置压缩的 MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      # 开启响应压缩
      enabled: true
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 8000
  sentinel:
    enabled: true
  hystrix:
    enabled: true
#设置feign指定日志输出级别为debug
logging:
  level:
    com:
      kerwin: debug