server:
  port: 9030
spring:
  application:
    name: xss-order
  profiles:
    #        多个文件用，隔开
    active: shardingTable
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: http://101.200.213.75:8848


