#logging:
#  config: classpath:log4j2-dev.xml
#  file:
#    path: logs/
#    name: xss-user.log
server:
  port: 9020

spring:
  application:
    name: user-service
  redis:
    # Redis本地服务器地址，注意要开启redis服务，即那个redis-server.exe
    host: 127.0.0.1
    # Redis服务器端口,默认为6379.若有改动按改动后的来
    port: 6379
    #Redis服务器连接密码，默认为空，若有设置按设置的来
    password:
    jedis:
      pool:
        # 连接池最大连接数，若为负数则表示没有任何限制
        max-active: 15
        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 20
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&charactorEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    oracleucp:
      port-number: 3306
  cloud:
    nacos:
      config:
        enabled: false
        #        配置中心地址
        server-addr:
      discovery:
        server-addr: http://localhost:8848


# 开启feign对sentinel的支持
feign:
  compression:
    request:
      # 开启请求压缩
      enabled: true
      # 配置压缩的 MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      # 开启响应压缩
      enabled: true
  client:
    config:
      #      提供方的服务名
      user-service:
        #请求日志级别
        loggerLevel: BASIC
      default:
        connectTimeout: 6000
        readTimeout: 8000
  sentinel:
    enabled: true # 开启feign对sentinel的支持
  #            1、Spring Cloud 2020之前的版本 只需在配置文件中设置feign.hystrix.enabled=true
  #         2、Spring Cloud 2020之后的版本 feign.hystrix.enabled=true无法解析，需要配置：feign.circuitbreaker.enabled=true
  hystrix:
    enabled: true
#设置feign指定日志输出级别为debug
logging:
  level:
    com:
      kerwin: debug