#logging:
#  config: classpath:log4j2-dev.xml
#  file:
#    path: logs/
#    name: xss-user.log
server:
    port: 9020

spring:
    application:
        name: xss-user
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&charactorEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: root
        password: 123456
        oracleucp:
            port-number: 3306
    cloud:
        nacos:
            config:
                import-check:
                    enabled: false
            discovery:
                server-addr: http://101.200.213.75:8848

mybatis:
  mapper-locations: classpath:com/xss/user/mapper/*.xml
  type-aliases-package: com.xss.user
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

